/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.ProjetoDAO;
import Model.Projeto;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author May
 */
public class TelaDetalheProjeto extends javax.swing.JFrame {

    private Projeto projetoAtual;

    /**
     * Creates new form TelaDetalheProjeto
     */
    public TelaDetalheProjeto() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Tema = new javax.swing.JLabel();
        lbl_Data = new javax.swing.JLabel();
        btn_Concluido = new javax.swing.JButton();
        btn_Curtir = new javax.swing.JButton();
        btnProcurar = new javax.swing.JButton();
        textfieldNomeProjeto = new javax.swing.JTextField();
        textfieldCriadorProjeto = new javax.swing.JTextField();
        lblCurtidas = new javax.swing.JLabel();
        textfieldLeituraCurtidas = new javax.swing.JTextField();
        textfieldIDInserido = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textfieldDescricaoProjeto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(169, 172, 200));

        lbl_Tema.setFont(new java.awt.Font("Gliker", 1, 42)); // NOI18N
        lbl_Tema.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Tema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Tema.setText("Detalhes do Projeto");
        lbl_Tema.setToolTipText("");
        lbl_Tema.setFocusable(false);
        lbl_Tema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_Data.setFont(new java.awt.Font("Gliker", 1, 12)); // NOI18N
        lbl_Data.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Data.setText("\"DD/MM/AA\"");

        btn_Concluido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Concluido.setText("Concluído");
        btn_Concluido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConcluidoActionPerformed(evt);
            }
        });

        btn_Curtir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Curtir.setText("Curtir");
        btn_Curtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CurtirActionPerformed(evt);
            }
        });

        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });

        textfieldNomeProjeto.setEditable(false);
        textfieldNomeProjeto.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome do Projeto"));

        textfieldCriadorProjeto.setEditable(false);
        textfieldCriadorProjeto.setBorder(javax.swing.BorderFactory.createTitledBorder("Criador do Projeto"));

        lblCurtidas.setFont(new java.awt.Font("Gliker", 1, 12)); // NOI18N
        lblCurtidas.setForeground(new java.awt.Color(255, 255, 255));
        lblCurtidas.setText("Curtidas:");

        textfieldLeituraCurtidas.setEditable(false);

        textfieldDescricaoProjeto.setColumns(20);
        textfieldDescricaoProjeto.setLineWrap(true);
        textfieldDescricaoProjeto.setRows(5);
        textfieldDescricaoProjeto.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição do Projeto"));
        jScrollPane1.setViewportView(textfieldDescricaoProjeto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(lbl_Tema, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textfieldIDInserido, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnProcurar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                                .addComponent(lblCurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textfieldLeituraCurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addComponent(textfieldNomeProjeto)
                            .addComponent(textfieldCriadorProjeto)
                            .addComponent(jScrollPane1))))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Curtir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162)
                .addComponent(btn_Concluido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_Tema, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProcurar)
                    .addComponent(textfieldIDInserido, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(textfieldNomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Data)
                    .addComponent(lblCurtidas)
                    .addComponent(textfieldLeituraCurtidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textfieldCriadorProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Concluido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Curtir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        try {
            String idText = textfieldIDInserido.getText();
            System.out.print(idText);
            if (!idText.isEmpty()) {
                int id = Integer.parseInt(idText);
                ProjetoDAO projetoDAO = new ProjetoDAO();
                Projeto projetoAtual = projetoDAO.buscarProjetoPorID(id);

                if (projetoAtual != null) {
                    System.out.println("Valor de ID digitado: " + idText);
                    atualizarDetalhesProjeto(projetoAtual);
                } else {
                    exibirMensagemErro("Projeto não encontrado.");
                }
            } else {
                exibirMensagemErro("Insira um número válido para o ID.");
            }
        } catch (NumberFormatException e) {
            exibirMensagemErro("Insira um número válido para o ID.");
        } catch (Exception ex) {
            exibirMensagemErro("Ocorreu um erro ao buscar o projeto por ID.");
        }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void btn_CurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CurtirActionPerformed
        if (projetoAtual != null) {
            ProjetoDAO projetoDAO = new ProjetoDAO();
            projetoDAO.incrementarCurtida(projetoAtual.getId());
            projetoAtual.setCurtidas(projetoAtual.getCurtidas() + 1);
            textfieldLeituraCurtidas.setText(String.valueOf(projetoAtual.getCurtidas()));
            JOptionPane.showMessageDialog(this, "Projeto curtido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, busque um projeto primeiro!");
        }
    }//GEN-LAST:event_btn_CurtirActionPerformed
    private void atualizarDetalhesProjeto(Projeto projeto) {
        textfieldNomeProjeto.setText(projeto.getNome());
        textfieldDescricaoProjeto.setText(projeto.getDescricao());
        textfieldCriadorProjeto.setText(projeto.getNomeResponsavel());
        textfieldLeituraCurtidas.setText(String.valueOf(projeto.getCurtidas()));
        lbl_Data.setText(new SimpleDateFormat("dd/MM/yyyy").format(projeto.getDataCriacao()));
        projetoAtual = projeto;
    }

    private void incrementarCurtida(int idProjeto) {
        ProjetoDAO projetoDAO = new ProjetoDAO();
        projetoDAO.incrementarCurtida(idProjeto);
        projetoAtual.setCurtidas(projetoAtual.getCurtidas() + 1);
        textfieldLeituraCurtidas.setText(String.valueOf(projetoAtual.getCurtidas()));
        JOptionPane.showMessageDialog(this, "Projeto curtido com sucesso!");
    }

    private boolean isNumeric(String str) {
        return str != null && str.matches("\\d+");
    }

    private void exibirMensagemErro(String mensagem) {
        JOptionPane.showMessageDialog(this, mensagem);
    }

    private void btn_ConcluidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConcluidoActionPerformed
        this.dispose();
        TelaProjetoUsuario telaProjetoUsuario = new TelaProjetoUsuario();
        telaProjetoUsuario.setVisible(true);
    }//GEN-LAST:event_btn_ConcluidoActionPerformed

    private javax.swing.JTextField curtidasTextField;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDetalheProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDetalheProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDetalheProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDetalheProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDetalheProjeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcurar;
    private javax.swing.JButton btn_Concluido;
    private javax.swing.JButton btn_Curtir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurtidas;
    private javax.swing.JLabel lbl_Data;
    private javax.swing.JLabel lbl_Tema;
    private javax.swing.JTextField textfieldCriadorProjeto;
    private javax.swing.JTextArea textfieldDescricaoProjeto;
    private javax.swing.JTextField textfieldIDInserido;
    private javax.swing.JTextField textfieldLeituraCurtidas;
    private javax.swing.JTextField textfieldNomeProjeto;
    // End of variables declaration//GEN-END:variables
}
