/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.OdsDAO;
import DAO.ProjetoDAO;
import Model.Projeto;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author May
 */
public class TelaCadastroProjeto extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroProjeto
     */
    public TelaCadastroProjeto() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Nome = new javax.swing.JLabel();
        txi_NomeProjeto = new javax.swing.JTextField();
        lbl_Descricao = new javax.swing.JLabel();
        lbl_Responsavel = new javax.swing.JLabel();
        txi_UsuarioResponsavel = new javax.swing.JTextField();
        lbl_ODS = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cmb_ODS = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        lbl_Tema = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(169, 172, 200));

        lbl_Nome.setFont(new java.awt.Font("Gliker", 1, 24)); // NOI18N
        lbl_Nome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Nome.setText("Nome:");

        txi_NomeProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txi_NomeProjetoActionPerformed(evt);
            }
        });

        lbl_Descricao.setFont(new java.awt.Font("Gliker", 1, 24)); // NOI18N
        lbl_Descricao.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Descricao.setText("Descrição:");

        lbl_Responsavel.setFont(new java.awt.Font("Gliker", 1, 24)); // NOI18N
        lbl_Responsavel.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Responsavel.setText("Responsável:");

        txi_UsuarioResponsavel.setForeground(new java.awt.Color(0, 0, 0));

        lbl_ODS.setFont(new java.awt.Font("Gliker", 1, 24)); // NOI18N
        lbl_ODS.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ODS.setText("ODS:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        cmb_ODS.setForeground(new java.awt.Color(255, 255, 255));
        cmb_ODS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cmb_ODS.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cmb_ODSAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cmb_ODS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ODSActionPerformed(evt);
            }
        });

        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lbl_Tema.setFont(new java.awt.Font("Gliker", 1, 42)); // NOI18N
        lbl_Tema.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Tema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Tema.setText("Cadastro De Projeto");

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(lbl_Tema, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
                    .addComponent(lbl_ODS, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txi_NomeProjeto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Descricao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Responsavel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txi_UsuarioResponsavel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_ODS, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Tema, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txi_NomeProjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Descricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Responsavel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txi_UsuarioResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ODS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_ODS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

            
    private void txi_NomeProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txi_NomeProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txi_NomeProjetoActionPerformed

    private void cmb_ODSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ODSActionPerformed

        }//GEN-LAST:event_cmb_ODSActionPerformed
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaProjetoUsuario telaProjetoUsuario = new TelaProjetoUsuario();
        telaProjetoUsuario.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cmb_ODSAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cmb_ODSAncestorAdded
        OdsDAO odsDAO = new OdsDAO();
        ArrayList<String> nomesODS = odsDAO.getNomesODS();
        System.out.println("ODS recuperadas do banco de dados: " + nomesODS);
        cmb_ODS.removeAllItems(); // Remove qualquer item existente
        for (String nomeODS : nomesODS) {
            System.out.println("Adicionando ODS na combobox: " + nomeODS);
        cmb_ODS.addItem(nomeODS);}
    }//GEN-LAST:event_cmb_ODSAncestorAdded

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    String nomeProjeto = txi_NomeProjeto.getText();
    String descricao = jTextArea1.getText();
    String usuarioResponsavel = txi_UsuarioResponsavel.getText();
    String nomeOds = (String) cmb_ODS.getSelectedItem();
    int numeroOds = cmb_ODS.getSelectedIndex() + 1;

    // Criar o projeto com os dados coletados
    Projeto projeto = new Projeto();
    projeto.setNome(nomeProjeto);
    projeto.setDescricao(descricao);
    projeto.setNomeResponsavel(usuarioResponsavel);
    projeto.setNumeroODS(numeroOds);
    projeto.setNomeODS(nomeOds);
    projeto.setStatus("Em Andamento"); // Defina o status conforme necessário

    // Inserir o projeto no banco de dados
    ProjetoDAO projetoDAO = new ProjetoDAO();
    projetoDAO.inserirProjeto(projeto);

    // Limpar os campos após o cadastro
    txi_NomeProjeto.setText("");
    jTextArea1.setText("");
    txi_UsuarioResponsavel.setText("");
    cmb_ODS.setSelectedIndex(0);

    // Exibir mensagem de sucesso para o usuário
    JOptionPane.showMessageDialog(this, "Projeto cadastrado com sucesso!");
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroProjeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cmb_ODS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbl_Descricao;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_ODS;
    private javax.swing.JLabel lbl_Responsavel;
    private javax.swing.JLabel lbl_Tema;
    private javax.swing.JTextField txi_NomeProjeto;
    private javax.swing.JTextField txi_UsuarioResponsavel;
    // End of variables declaration//GEN-END:variables
}
